"""Single source of truth for the product version shown in the tray menu.

``APP_VERSION`` is bumped manually per build; ``BUILD_TAG`` is the git
short hash written by the PyInstaller spec at build time (falls back to
"dev" when git is unavailable or the spec never ran).
"""

APP_VERSION = "0.9.3"

try:
    from core._build_tag import BUILD_TAG  # generated by the spec at build time
except ImportError:
    BUILD_TAG = "dev"


def version_label() -> str:
    return f"{APP_VERSION} ({BUILD_TAG})"